# Generated by Django 5.2.6 on 2025-10-29 20:23

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Clinics',
            },
        ),
        migrations.CreateModel(
            name='EmergencyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Week A Rotation', '4 On / 2 Off'", max_length=100, unique=True)),
                ('length_in_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='The part of the email before @phc.gov.bh', max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Must be a unique Bahraini phone number.', max_length=128, region='BH', unique=True)),
                ('employee_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('role', models.CharField(choices=[('NURSE', 'Nurse'), ('MAS', 'MAS (Auxiliary)'), ('MANAGER', 'Nurse Manager')], default='NURSE', max_length=7)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group', models.CharField(blank=True, help_text='e.g., Group 1, Group 2, Clinic', max_length=50, null=True)),
                ('committee', models.CharField(blank=True, help_text='e.g., Medical Equipment, Emergency, Health Promotion', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('NOT_COMPLETED', 'Not Completed')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Explain why this assignment is split, if applicable.')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main_app.monthlytask')),
            ],
            options={
                'ordering': ['group', 'task__name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='RotationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='The day in the rotation sequence (e.g., 1, 2, 3...)')),
                ('is_day_off', models.BooleanField(default=False)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main_app.rotation')),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.shifttype')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('rotation', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('NOT_COMPLETED', 'Not Completed')], default='PENDING', max_length=15)),
                ('team_leader_notes', models.TextField(blank=True, help_text='Notes from the team leader.', null=True)),
                ('is_approved_by_manager', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignments', models.ManyToManyField(blank=True, to='main_app.assignment')),
                ('clinics', models.ManyToManyField(blank=True, to='main_app.clinic')),
                ('emergency_roles', models.ManyToManyField(blank=True, to='main_app.emergencyrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='main_app.shifttype')),
                ('sub_assignments', models.ManyToManyField(blank=True, to='main_app.subassignment')),
            ],
            options={
                'unique_together': {('staff', 'date', 'shift_type')},
            },
        ),
    ]
