# Generated by Django 5.2.6 on 2025-09-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('MAS', 'MAS (Auxiliary)'), ('MANAGER', 'Nurse Manager')], default='NURSE', max_length=7),
        ),
    ]
