# Generated by Django 5.2.6 on 2025-09-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Week A Rotation', '4 On / 2 Off'", max_length=100, unique=True)),
                ('length_in_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RotationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='The day in the rotation sequence (e.g., 1, 2, 3...)')),
                ('is_day_off', models.BooleanField(default=False)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main_app.rotation')),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.shifttype')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('rotation', 'day_number')},
            },
        ),
    ]
